"""add MaterialTxnAudit

Revision ID: 0bb5c01104de
Revises: 80acd99cc7aa
Create Date: 2025-11-04 16:22:26.974420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb5c01104de'
down_revision = '80acd99cc7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_txn_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changed_fields', sa.String(length=255), nullable=True),
    sa.Column('old_json', sa.Text(), nullable=True),
    sa.Column('new_json', sa.Text(), nullable=True),
    sa.Column('editor_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_txn_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_txn_audits_editor_ts'), ['editor_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_txn_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_txn_audits_editor_ts'))

    op.drop_table('material_txn_audits')
    # ### end Alembic commands ###
