"""add audit table

Revision ID: 80acd99cc7aa
Revises: adda3796fee5
Create Date: 2025-11-04 15:42:30.217978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80acd99cc7aa'
down_revision = 'adda3796fee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_txns', schema=None) as batch_op:
        batch_op.alter_column('ts',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('entry_ts',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('uom',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('ref_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('ref_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_material_txns_entry_ts'), ['entry_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_txns_entry_ts'))
        batch_op.alter_column('ref_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ref_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('uom',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('entry_ts',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('ts',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
