"""FG inventory & txns

Revision ID: 9711ecb3985d
Revises: 0bb5c01104de
Create Date: 2025-11-05 14:32:37.920224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9711ecb3985d'
down_revision = '0bb5c01104de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fg_txn_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changed_fields', sa.String(length=255), nullable=True),
    sa.Column('old_json', sa.Text(), nullable=True),
    sa.Column('new_json', sa.Text(), nullable=True),
    sa.Column('editor_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fg_txn_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fg_txn_audits_editor_ts'), ['editor_ts'], unique=False)

    op.create_table('fg_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_on_hand', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fg_inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fg_inventories_product_id'), ['product_id'], unique=True)

    op.create_table('fg_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('entry_ts', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_in', sa.Float(), nullable=True),
    sa.Column('qty_out', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fg_txns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fg_txns_entry_ts'), ['entry_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_fg_txns_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fg_txns_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fg_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fg_txns_ts'))
        batch_op.drop_index(batch_op.f('ix_fg_txns_product_id'))
        batch_op.drop_index(batch_op.f('ix_fg_txns_entry_ts'))

    op.drop_table('fg_txns')
    with op.batch_alter_table('fg_inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fg_inventories_product_id'))

    op.drop_table('fg_inventories')
    with op.batch_alter_table('fg_txn_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fg_txn_audits_editor_ts'))

    op.drop_table('fg_txn_audits')
    # ### end Alembic commands ###
